# Generated by Django 4.1.7 on 2023-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
