DEBUG = False

# TODO: Change
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME = False
EMAIL_ACTIVATION_AFTER_CHANGING = True

SERVER_EMAIL = 'support_aacdev@mapn.ro'