FROM python:3.8.10-slim

WORKDIR /usr/src/app

# Solve OS dependencies
RUN apt update 
RUN apt install -y gcc python3-dev build-essential libpq-dev	

# Copy project files
COPY source/ /usr/src/app/

# Copy entrypoint script 
COPY docker/entrypoint_dev_django.sh ./entrypoint_dev_django.sh

# Solve Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# 
ENTRYPOINT ["/usr/src/app/docker/entrypoint_dev_django.sh"]
