# Generated by Django 4.1.7 on 2023-05-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localitate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('auto', models.CharField(max_length=5)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='UM',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('indicativ', models.CharField(max_length=20)),
                ('denumire', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('crisc', models.BooleanField(default=False)),
                ('localitate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.localitate')),
            ],
        ),
        migrations.CreateModel(
            name='UserGrad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('denumire_grad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('ip_public', models.CharField(max_length=100)),
                ('nume_isp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stare', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='stare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.websitestate'),
        ),
        migrations.AddField(
            model_name='website',
            name='um_beneficiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiar_de_umuri', to='websites.um'),
        ),
        migrations.AddField(
            model_name='website',
            name='um_detinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detinator_de_umuri', to='websites.um'),
        ),
        migrations.AddField(
            model_name='website',
            name='um_gazda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gazda_de_umuri', to='websites.um'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('email_intra', models.CharField(max_length=100)),
                ('email_inter', models.CharField(max_length=100)),
                ('telefon_rtp', models.CharField(max_length=100)),
                ('telefon_mobil', models.CharField(blank=True, max_length=100, null=True)),
                ('grad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.usergrad')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.websitestate')),
                ('unitate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.um')),
            ],
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ca_semnatar', models.CharField(blank=True, max_length=100, null=True)),
                ('data_expirare', models.DateField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
    ]
